# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
x = np.zeros(10)

3. Create a vector with values ranging from 10 to 49

In [3]:
v = np.arange(10,49)

4. Find the shape of previous array in question 3

In [9]:
v.shape

(39,)

5. Print the type of the previous array in question 3

In [10]:
v.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [11]:
np.__version__

'1.19.2'

7. Print the dimension of the array in question 3


In [12]:
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/SAQ/anaconda3/envs/NumpyAssignments\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/SAQ/anaconda3/envs/NumpyAssignments\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/SAQ/anaconda3/envs/NumpyAssignments\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/SAQ/anaconda3/envs/NumpyAssignments\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/SAQ/anaconda3/envs/NumpyAssignments\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/SAQ/anaconda3/envs/NumpyAssignments\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/SAQ/anaconda3/envs/NumpyAssignments\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), 

8. Create a boolean array with all the True values

In [13]:
np.ones((5),dtype=bool)

array([ True,  True,  True,  True,  True])

9. Create a two dimensional array




In [14]:
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

10. Create a three dimensional array



In [15]:
np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [16]:
v[::-1]

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

12. Create a null vector of size 10 but the fifth value which is 1 

In [18]:
x = x.astype(int)
x[5]=1

13. Create a 3x3 identity matrix

In [19]:
idmax = np.identity(3)

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [22]:
arr = np.array([1,2,3,4,5])
arr = arr.astype(float)

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [24]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [25]:
np.equal(arr1,arr2)

array([[False, False, False],
       [False, False, False]])

17. Extract all odd numbers from arr with values(0-9)

In [31]:
arr = arr.astype(int)
arr[arr%2==1]

array([1, 3, 5])

18. Replace all odd numbers to -1 from previous array

In [19]:
arr = np.array([1,2,3,4,5])
arrod = arr [arr % 2 == 1]
arrod = [arr % 2 == 1]
arr[arrod] = -1
print(arr)
#outcome on my pc [-1  2 -1  4 -1] with future warning

[-1  2 -1  4 -1]


<ipython-input-19-57ddc2dd50cb>:4: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  arr[arrod] = -1


19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [34]:
arr = np.arange(10)
for i in arr:
    if i > 4 and i < 9:
        arr[i]=12
print(arr)


[ 0  1  2  3  4 12 12 12 12  9]


20. Create a 2d array with 1 on the border and 0 inside

In [36]:
_2doz = np.ones((3,3))
_2doz[1:-1,1:-1] = 0
print(_2doz)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [4]:
import numpy as np
arr2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr2d[1][1] = 12
print(arr2d)

[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [6]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0] = (64)
print(arr3d)

[[[64 64 64]
  [64 64 64]]

 [[ 7  8  9]
  [10 11 12]]]


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [7]:
_2darray = np.array([[1,2,3],[4,5,6]])
_onedarray = _2darray.flatten()
print(_onedarray)

[1 2 3 4 5 6]


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [2]:
import numpy as np
_2darray = np.array([[1,2,3,4,5],[6,7,8,9,10]])
_onedarray = _2darray[1][1]
print(_onedarray)

7


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [3]:
_2darray = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(_2darray.T[0])

[1 6]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [4]:
_10ar = np.random.random((10,10))
print(_10ar)
_10armin,_10armax = _10ar.min(), _10ar.max()
print(_10armin," ",_10armax)

[[0.49856651 0.79412235 0.66432723 0.66557571 0.65286425 0.60305448
  0.83247934 0.52465708 0.08248085 0.77860732]
 [0.6047046  0.12345227 0.2728233  0.89595771 0.56390227 0.59866773
  0.23716482 0.73170243 0.63831604 0.85464087]
 [0.13483322 0.15252379 0.49207264 0.48734072 0.40144679 0.33962257
  0.45806184 0.85944071 0.55842056 0.00832239]
 [0.78926877 0.18215377 0.11461398 0.88364501 0.55398446 0.30351659
  0.38713541 0.6510852  0.59958705 0.46281871]
 [0.56532591 0.50208145 0.89271336 0.03210148 0.72797178 0.3103878
  0.83760798 0.91782479 0.45662323 0.25962873]
 [0.73923562 0.78413114 0.79552988 0.90366055 0.60599813 0.54069057
  0.93691099 0.74402069 0.59557927 0.85372748]
 [0.37376276 0.61726897 0.07273818 0.01804326 0.45533513 0.85434439
  0.30511362 0.37735947 0.17226771 0.83447161]
 [0.72151646 0.24944585 0.22444019 0.33818127 0.78101314 0.8351106
  0.73529058 0.2038541  0.36871756 0.54813526]
 [0.35659007 0.94381431 0.17314793 0.96684819 0.53532584 0.15084466
  0.8409396  0

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [5]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a,b))

[2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [7]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(a == b)
print(np.where(a==b))

[False  True False  True False  True False  True False False]
(array([1, 3, 5, 7], dtype=int64),)


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [34]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
datanotWill = data[(names != 'Will')]
print(datanotWill)

[[-1.09817859  1.59969961 -0.77560227  0.97448947]
 [ 0.88500493 -0.63932989 -1.08008855 -0.13350581]
 [ 1.1844417  -1.43744829 -0.75701291  0.02083666]
 [-0.36932364 -3.20427584  0.83172166 -0.08946619]
 [ 1.62222391  0.095641   -0.38949816 -0.5856718 ]]


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [35]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
notwj = data[(names != 'Will') | (names != 'Joe')]
print(notwj)

[[ 0.91131261  1.05397387 -1.56783458  0.45641258]
 [ 0.21646379  0.66424964  1.05054222 -0.72517751]
 [ 0.80426567 -0.5726357  -0.43092414 -1.06851436]
 [ 1.05309673  0.3526467   0.3872631   0.0515325 ]
 [-0.49885173 -1.30526028  0.17477725 -0.02810368]
 [-1.35394773  0.55367892 -0.75822418 -0.08444716]
 [-1.49258427 -0.09973878  0.05039936  0.30607914]]


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [2]:
import numpy as np
_2dar1t15 = np.random.uniform(5,10, size=(5,3))
print(_2dar1t15)

[[6.05734295 7.78678686 7.03930277]
 [5.33369769 9.26860248 5.37770286]
 [9.48858017 7.20296853 9.35013386]
 [5.59639177 9.74678224 7.79196888]
 [5.75180902 6.0080755  9.64530448]]


32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [3]:
_2dar1t16 = np.arange(1,17,).reshape(2,2,4)
print(_2dar1t16)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


33. Swap axes of the array you created in Question 32

In [4]:

print(np.swapaxes(_2dar1t16,0,2))

[[[ 1  9]
  [ 5 13]]

 [[ 2 10]
  [ 6 14]]

 [[ 3 11]
  [ 7 15]]

 [[ 4 12]
  [ 8 16]]]


34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [5]:
sqroot = np.arange(1,11)
sqrootx = np.sqrt(sqroot)
for i in range(len(sqrootx)):
    if sqrootx[i] < 0.5:
        sqrootx[i] = 0
print(sqrootx)

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [6]:
_1starr = np.random.random(12)
_2ndarr = np.random.random(12)
print(_1starr)
print(_2ndarr)
_maxarr = np.maximum(_1starr,_2ndarr)
print(_maxarr)

[0.39643366 0.39640112 0.89846947 0.75365819 0.96804061 0.80028166
 0.18242815 0.68112543 0.69129617 0.90249131 0.38976917 0.14859555]
[0.08254025 0.60659867 0.15959166 0.36203249 0.35992231 0.53255164
 0.38533423 0.30540172 0.79523826 0.14342956 0.84512668 0.82065397]
[0.39643366 0.60659867 0.89846947 0.75365819 0.96804061 0.80028166
 0.38533423 0.68112543 0.79523826 0.90249131 0.84512668 0.82065397]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [7]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(np.unique(names))

['Bob' 'Joe' 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [8]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
print(a[b[np.searchsorted(b,a)] !=  a])

[1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [9]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
sampleArray = np.delete(sampleArray, [1], axis=1)
sampleArray = np.insert(sampleArray, 1, newColumn, axis=1)
print(sampleArray)


[[34 10 73]
 [82 10 12]
 [53 10 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [10]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
print(np.dot(x,y))

[[ 28.  64.]
 [ 67. 181.]]


40. Generate a matrix of 20 random values and find its cumulative sum

In [11]:
A = np.random.random( size=(5,5))
cul = np.cumsum(A)
print(cul)

[ 0.35792961  0.80658412  1.15958808  1.99017153  2.38668781  2.90540242
  3.2978733   3.37594874  3.7222452   4.66537654  4.85300177  5.78389888
  6.32825264  6.80704264  6.92506333  7.4208725   8.18835323  8.51551443
  9.10507203  9.89281491 10.62269433 11.25746526 12.24345255 12.7562094
 12.9003122 ]
